In [1]:
import json
import pandas as pd
from IPython.display import display
pd.set_option('display.precision', 10)
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
# %matplotlib qt

uuid = "944A16A5-9D5D-4348-B532-10B926BB86A1" # up / down wrist motion
uuid = "2662B396-20B2-4EF4-903D-915CDD2660C0" # Around and then over a bit
# uuid = "8AA26238-1BAA-4C00-82E2-6E5EE496A0DE"
# uuid = "A4E3E98D-2110-4C75-8C4D-AADC0E5F6B2D"
uuid = "8E101B8C-D588-4416-BA98-678D218CA125"
uuid = "792DBF78-CCE2-44A2-BC1D-D618789F099A"
uuid = "99AAC7DE-4106-43AB-AA80-F5816AB4DB85"

def import_uuid(uuid):
    
    # Define the file path
    raw_data_filepath = "Data/" + uuid + ".json"
    timestamps_filepath = "Data/Timestamps_" + uuid + ".json"
    
    raw_df = import_data_json(raw_data_filepath)
    timestamps_df = import_timestamp_json(timestamps_filepath)
    return (raw_df, timestamps_df)

    

def import_data_json(filepath):
    # Read the JSON data from the file
    with open(filepath, 'r') as file:
        data = json.load(file)

    # Extract workoutDatas
    workout_datas = data["workoutDatas"]

    # Create a DataFrame
    df = pd.json_normalize(workout_datas)
    return df

def import_timestamp_json(timestamps_filepath):
    # return pd.read_json(timestamps_filepath)
    with open(timestamps_filepath, 'r') as file:
        data = json.load(file)

    # Step 2: Structure the data
    # Create a dictionary to hold structured data
    structured_data = {
        "startTime": data["startTime"],
        "endTime": data["endTime"],
        "groundLeaveTimes": data["groundLeaveTimes"],
        "airLeaveTimes": data["airLeaveTimes"]
    }

    # Step 3: Create the DataFrame
    # If you want to have each time in a separate row, you can normalize the lists
    df_ground = pd.DataFrame(structured_data["groundLeaveTimes"], columns=["groundLeaveTimes"])
    df_air = pd.DataFrame(structured_data["airLeaveTimes"], columns=["airLeaveTimes"])

    # Combine into a single DataFrame if needed
    df = pd.concat([df_ground, df_air], axis=1)

    # Add startTime and endTime to every row if needed
    df["startTime"] = structured_data["startTime"]
    df["endTime"] = structured_data["endTime"]
    return df
    
raw_df, timestamps_df = import_uuid(uuid)
mask = (raw_df['time'] >= timestamps_df['startTime'][0]) * (raw_df['time'] <= timestamps_df['endTime'][0])
trimmed_raw_df = raw_df[mask]
trimmed_raw_df["time"] = trimmed_raw_df["time"].apply(lambda x: x - timestamps_df["startTime"][0])
timestamps_df["airLeaveTimes"] = timestamps_df["airLeaveTimes"].apply(lambda x: x - timestamps_df["startTime"][0])
end_time = timestamps_df["endTime"][0] - timestamps_df["startTime"][0]
display(trimmed_raw_df)
display(timestamps_df["airLeaveTimes"])


C:\Users\thoma\AppData\Local\Temp\ipykernel_29284\1860827166.py:74: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trimmed_raw_df["time"] = trimmed_raw_df["time"].apply(lambda x: x - timestamps_df["startTime"][0])


time                                    id  heartRate  \
635      0.0035848618  A0AFAFCF-CE07-46F0-A6AF-4397965FB352         59   
636      0.0137836933  A5EA8721-0535-46E9-8722-D263F34CABF2         59   
637      0.0239989758  FC88C84D-7C34-4A5F-A944-504E36B983CF         59   
638      0.0327928066  D944727E-4C7D-4BA9-A3EF-3FF02DA2C4D6         59   
639      0.0447247028  00E12E46-A60C-49DA-992A-762FA6DB327C         59   
...               ...                                   ...        ...   
11161  111.7581348419  9F4B7DFF-804A-4D09-8ABC-BDD49A12FD08        122   
11162  111.7629017830  C4F7AFDF-3CDF-4412-9EE9-9322DFAB5766        122   
11163  111.7685627937  DA2EA432-C9AF-4731-BEA9-1DB5C761D4A4        122   
11164  111.7739698887  0BEC5105-E63D-46FE-8C0C-C46A041D017B        122   
11165  111.7862207890  ECE10A6B-CD2E-48D6-842D-D9F8058FD112        122   

      workoutType  motion.magneticField.z  motion.magneticField.x  \
635         Situp           41.1064453125          -16.2679138184   
636         Situp           41.2516479492          -15.9732360840   
637         Situp           41.1845703125          -15.5014648438   
638         Situp           41.0240478516          -15.3656616211   
639         Situp           41.5241088867          -15.3257141113   
...           ...                     ...                     ...   
11161       Situp           39.4486694336           -4.5259094238   
11162       Situp           39.5006713867           -4.1711425781   
11163       Situp           39.2673950195           -4.3647460938   
11164       Situp           39.1791992188           -3.9233398438   
11165       Situp           39.6568603516           -3.7833251953   

       motion.magneticField.y  motion.acceleration.z  motion.acceleration.x  \
635            -13.5095672607           0.0098853111           0.0253720880   
636            -13.3244476318           0.0094820261           0.0274597406   
637            -13.1271209717           0.0143240690           0.0157210827   
638            -12.9457244873           0.0217298269           0.0045726895   
639            -12.9057769775           0.0391298532           0.0014925599   
...                       ...                    ...                    ...   
11161          -29.3167114258          -0.0270351768           0.0056752861   
11162          -29.1807403564           0.0359960198           0.0094667375   
11163          -29.0579071045           0.0602967739           0.0090401769   
11164          -29.0066070557           0.0548523068           0.0463493168   
11165          -28.8048706055           0.0324288607           0.0786449015   

       motion.acceleration.y  ...  motion.rotationMatrix.m13  \
635            -0.0501860678  ...               0.6005216241   
636            -0.0341082625  ...               0.5990234017   
637            -0.0330852456  ...               0.5975844860   
638            -0.0452974960  ...               0.5962474346   
639            -0.0505077280  ...               0.5949221849   
...                      ...  ...                        ...   
11161          -0.0421833992  ...               0.3961018920   
11162          -0.0632137954  ...               0.3937439919   
11163          -0.0841110349  ...               0.3897011876   
11164          -0.0695360601  ...               0.3890007734   
11165          -0.0623796284  ...               0.3885051310   

       motion.rotationMatrix.m33  motion.rotationMatrix.m21  \
635                -0.7989068031              -0.7892061472   
636                -0.7999203205              -0.7872070074   
637                -0.8008462787              -0.7848877907   
638                -0.8016648293              -0.7824921012   
639                -0.8024535179              -0.7801520228   
...                          ...                        ...   
11161              -0.8603175282              -0.7456378341   
11162              -0.8614799976              -0.7442022562   
11163         

0       3.5709590912
1       7.3710031509
2      11.2009625435
3      14.9909555912
4      18.4903991222
5      21.7402029037
6      25.1109051704
7      28.7609484196
8      32.3709535599
9      36.2109022141
10     40.4909000397
11     43.7909100056
12     47.2309548855
13     50.8605346680
14     54.5009567738
15     58.5109500885
16     62.3001129627
17     65.9109506607
18     69.7209010124
19     73.2209177017
20     76.7809531689
21     80.5499444008
22     83.9709529877
23     87.5709609985
24     91.1709496975
25     95.4009451866
26     99.0705158710
27    102.5909085274
28    106.0209257603
29    109.2199797630
Name: airLeaveTimes, dtype: float64

In [2]:
# fig1, axs = plt.subplots(2,3)
# axs[0][0].plot(trimmed_raw_df["time"], trimmed_raw_df["motion.acceleration.x"])
# axs[0][1].plot(trimmed_raw_df["time"], trimmed_raw_df["motion.acceleration.y"])
# axs[0][2].plot(trimmed_raw_df["time"], trimmed_raw_df["motion.acceleration.z"])
# axs[1][0].plot(trimmed_raw_df["time"], trimmed_raw_df["motion.pitch"])
# axs[1][1].plot(trimmed_raw_df["time"], trimmed_raw_df["motion.roll"])
# axs[1][2].plot(trimmed_raw_df["time"], trimmed_raw_df["motion.yaw"])
# for timestamp in timestamps_df["airLeaveTimes"]:
#     axs[0][0].axvline(timestamp, color='r')
#     axs[0][1].axvline(timestamp, color='r')
#     axs[0][2].axvline(timestamp, color='r')
#     axs[1][0].axvline(timestamp, color='r')
#     axs[1][1].axvline(timestamp, color='r')
#     axs[1][2].axvline(timestamp, color='r')
# fig1.set_size_inches(24,18)
# fig1.tight_layout()


In [3]:
spacing = 0.1
start_10s_times = np.arange(0, np.ceil(end_time)-10, spacing)
# list(range(0, int(np.ceil(end_time))-10, 0.1))
start_7s_times = np.arange(0, np.ceil(end_time)-7, spacing)#list(range(0, int(np.ceil(end_time))-7, 0.1))
print(start_7s_times)

[0.000e+00 1.000e-01 2.000e-01 ... 1.047e+02 1.048e+02 1.049e+02]


In [4]:
trimmed_raw_df.pop("id")
trimmed_raw_df.pop("motion.magneticField.x")
trimmed_raw_df.pop("motion.magneticField.y")
trimmed_raw_df.pop("motion.magneticField.z")
trimmed_raw_df.pop("heartRate")
trimmed_raw_df.pop("workoutType")
trimmed_raw_df.pop("motion.rotationMatrix.m11")
trimmed_raw_df.pop("motion.rotationMatrix.m12")
trimmed_raw_df.pop("motion.rotationMatrix.m13")
trimmed_raw_df.pop("motion.rotationMatrix.m21")
trimmed_raw_df.pop("motion.rotationMatrix.m22")
trimmed_raw_df.pop("motion.rotationMatrix.m23")
trimmed_raw_df.pop("motion.rotationMatrix.m31")
trimmed_raw_df.pop("motion.rotationMatrix.m32")
trimmed_raw_df.pop("motion.rotationMatrix.m33")

635     -0.7989068031
636     -0.7999203205
637     -0.8008462787
638     -0.8016648293
639     -0.8024535179
             ...     
11161   -0.8603175282
11162   -0.8614799976
11163   -0.8644469380
11164   -0.8654206991
11165   -0.8664358854
Name: motion.rotationMatrix.m33, Length: 10531, dtype: float64

In [5]:
datasets_7s = []
timestamps_7s = []
datasets_10s = []
timestamps_10s = []

sample_frequency = 100
for start_time in start_10s_times:
    mask = (trimmed_raw_df["time"] > start_time).tolist()
    first_survive = mask.index(1)
    mask = np.array(mask)
    mask[first_survive + 10*sample_frequency:] = 0
    start_time_dataset = trimmed_raw_df[mask]
    start_time_dataset["time"] = start_time_dataset["time"] - start_time
    datasets_10s.append(start_time_dataset)
    mask = (timestamps_df["airLeaveTimes"] > start_time) * (timestamps_df["airLeaveTimes"] < start_time +10)
    start_time_timestamps = np.array(timestamps_df["airLeaveTimes"].tolist())[mask]
    start_time_timestamps = start_time_timestamps - start_time
    timestamps_10s.append(start_time_timestamps)
for start_time in start_7s_times:
    mask = (trimmed_raw_df["time"] > start_time).tolist()
    first_survive = mask.index(1)
    mask = np.array(mask)
    mask[first_survive + 7*sample_frequency:] = 0
    start_time_dataset = trimmed_raw_df[mask]
    start_time_dataset["time"] = start_time_dataset["time"] - start_time
    datasets_7s.append(start_time_dataset)
    mask = (timestamps_df["airLeaveTimes"] > start_time) * (timestamps_df["airLeaveTimes"] < start_time +7)
    start_time_timestamps = np.array(timestamps_df["airLeaveTimes"].tolist())[mask]
    start_time_timestamps = start_time_timestamps - start_time
    timestamps_7s.append(start_time_timestamps)
# datasets_7s_scaled = scale.fit_transform(datasets_7s)
display(datasets_7s)
display(timestamps_7s)

C:\Users\thoma\AppData\Local\Temp\ipykernel_29284\1042713959.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_time_dataset["time"] = start_time_dataset["time"] - start_time
C:\Users\thoma\AppData\Local\Temp\ipykernel_29284\1042713959.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_time_dataset["time"] = start_time_dataset["time"] - start_time


[              time  motion.acceleration.z  motion.acceleration.x  \
 635   0.0035848618           0.0098853111           0.0253720880   
 636   0.0137836933           0.0094820261           0.0274597406   
 637   0.0239989758           0.0143240690           0.0157210827   
 638   0.0327928066           0.0217298269           0.0045726895   
 639   0.0447247028           0.0391298532           0.0014925599   
 ...            ...                    ...                    ...   
 1330  7.4820897579          -0.0104304254           0.0340985060   
 1331  7.4928996563          -0.0242856741           0.0293629169   
 1332  7.5015146732          -0.0311860442           0.0433015227   
 1333  7.5102388859          -0.0417497158           0.0586267710   
 1334  7.5462319851          -0.0501309037           0.0754131675   
 
       motion.acceleration.y   motion.roll    motion.yaw  motion.pitch  \
 635           -0.0501860678 -2.4970177124  2.2313557035 -0.0334992177   
 636           -0.0341

[array([3.57095909]),
 array([3.47095909]),
 array([3.37095909]),
 array([3.27095909]),
 array([3.17095909, 6.97100315]),
 array([3.07095909, 6.87100315]),
 array([2.97095909, 6.77100315]),
 array([2.87095909, 6.67100315]),
 array([2.77095909, 6.57100315]),
 array([2.67095909, 6.47100315]),
 array([2.57095909, 6.37100315]),
 array([2.47095909, 6.27100315]),
 array([2.37095909, 6.17100315]),
 array([2.27095909, 6.07100315]),
 array([2.17095909, 5.97100315]),
 array([2.07095909, 5.87100315]),
 array([1.97095909, 5.77100315]),
 array([1.87095909, 5.67100315]),
 array([1.77095909, 5.57100315]),
 array([1.67095909, 5.47100315]),
 array([1.57095909, 5.37100315]),
 array([1.47095909, 5.27100315]),
 array([1.37095909, 5.17100315]),
 array([1.27095909, 5.07100315]),
 array([1.17095909, 4.97100315]),
 array([1.07095909, 4.87100315]),
 array([0.97095909, 4.77100315]),
 array([0.87095909, 4.67100315]),
 array([0.77095909, 4.57100315]),
 array([0.67095909, 4.47100315]),
 array([0.57095909, 4.371003

In [6]:
# Splitting the data into training and test datasets
split_7s = int(len(datasets_7s) * 0.8)
datasets_7s_training, datasets_7s_testing = datasets_7s[:split_7s], datasets_7s[split_7s:]
timestamps_7s_training, timestamps_7s_testing = timestamps_7s[:split_7s], timestamps_7s[split_7s:]

split_10s = int(len(datasets_10s) * 0.8)
datasets_10s_training, datasets_10s_testing = datasets_10s[:split_10s], datasets_10s[split_10s:]
timestamps_10s_training, timestamps_10s_testing = timestamps_10s[:split_10s], timestamps_10s[split_10s:]

In [7]:
for dataset_7s in datasets_7s:
    print(len(dataset_7s))

700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700
700


In [8]:
# from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestRegressor
# from sklearn.metrics import mean_squared_error

# model = RandomForestRegressor(n_estimators=100, random_state=42)
# model.fit(datasets_7s_training, timestamps_7s_training)

# # Evaluate the model
# y_pred = model.predict(datasets_7s_testing)
# mse = mean_squared_error(timestamps_7s_testing, y_pred)
# print(f'Mean Squared Error: {mse}')

# # Plot actual vs predicted
# plt.figure(figsize=(10, 5))
# plt.plot(timestamps_7s_testing.values, label='Actual')
# plt.plot(y_pred, label='Predicted')
# plt.legend()
# plt.show()

# # Predict future events
# # # For example, if you want to predict the next timestamp based on the last known data point
# # last_row = df.iloc[-1][['a', 'b', 'c', 'd', 'e', 'f', 'a_shifted', 'b_shifted', 'c_shifted', 'd_shifted', 'e_shifted', 'f_shifted']]
# future_event_prediction = model.predict([last_row])
# print(f'Future Event Prediction: {future_event_prediction}')

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error

# Load the dataset
def load_data(file_path):
    data = pd.read_csv(file_path)
    return data

# Preprocess the data
def preprocess_data(datasets, timestamp_datasets):
    evaluated_datasets = []
    evaluated_timestamps = []
    for dataset in datasets:
        X = dataset.values.reshape(-1,10)
        evaluated_datasets.append(X)
    # for timestamps in timestamp_datasets:
    #     y = timestamps["airLeaveTimes"].values
    #     evaluated_timestamps.append(y)
    # print(y)
    return evaluated_datasets, timestamp_datasets

# Extract features (in this case, we will use position as the feature directly)
def extract_features(X):
    return X

# Train the model
def train_model(X_train, y_train):
    scaler_X = StandardScaler()
    scaler_y = StandardScaler()

    X_train_scaled = scaler_X.fit_transform(X_train)
    y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()

    model = SVR(kernel='rbf', C=1e3, gamma=0.1)
    model.fit(X_train_scaled, y_train_scaled)

    return model, scaler_X, scaler_y

# Predict timestamps
def predict_timestamps(model, scaler_X, scaler_y, X_test):
    X_test_scaled = scaler_X.transform(X_test)
    y_pred_scaled = model.predict(X_test_scaled)
    y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1))
    return y_pred

In [10]:
# X, y = preprocess_data(datasets_7s_training, timestamps_7s_training)
# print(X)
# print(y)
# # Extract features
# X_features = extract_features(X)

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X_features, y, test_size=0.2, random_state=42)

# # Train the model
# model, scaler_X, scaler_y = train_model(X_train, y_train)

# # Predict timestamps for the test set
# y_pred = predict_timestamps(model, scaler_X, scaler_y, X_test)

# # Evaluate the model
# mae = mean_absolute_error(y_test, y_pred)
# print(f'Mean Absolute Error: {mae}')

# # Plot results
# plt.figure(figsize=(10, 5))
# plt.scatter(y_test, y_pred, color='blue', label='Predicted vs Actual')
# plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', lw=2)
# plt.xlabel('Actual Timestamps')
# plt.ylabel('Predicted Timestamps')
# plt.title('Actual vs Predicted Timestamps')
# plt.legend()
# plt.show()

In [11]:
# print(X[1][300])
# print(np.shape(X))

In [12]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, LSTM, Dense, TimeDistributed, RepeatVector
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        print(e)

# Assuming X is your input data (1000 samples of 10x600 matrices)
# and Y is your output data (list of variable-length sequences)
# X = np.random.rand(1000, 10, 600, 1)  # Example input data
# Y = [np.random.rand(np.random.randint(1, 50), 1) for _ in range(1000)]  # Example variable-length output sequences
X, Y = preprocess_data(datasets_7s_training, timestamps_7s_training)
print(np.shape(X))
# X = np.random.rand(1000, 10, 600, 1)  # 1000 samples of 10x600 matrices with 1 channel
# Y = [np.random.rand(np.random.randint(1, 50), 1) for _ in range(1000)]  # Example variable-length output sequences

# Padding the output sequences
max_seq_length = max(len(seq) for seq in Y)
Y_padded = pad_sequences(Y, maxlen=max_seq_length, padding='post', dtype='float32')
num_samples = len(X)
Y_padded = Y_padded.reshape(num_samples, max_seq_length, 1)
X = np.array(X).reshape(num_samples, 10, 700, 1)
print(np.shape(Y_padded))
# print(Y_padded)

# Splitting data into training and validation sets
X_train, X_val, Y_train, Y_val = train_test_split(X, Y_padded, test_size=0.2, random_state=42)

# Verify that the split is done correctly
print(f"X_train shape: {np.shape(X_train)}")
print(f"Y_train shape: {np.shape(Y_train)}")
print(f"X_val shape: {np.shape(X_val)}")
print(f"Y_val shape: {np.shape(Y_val)}")

# Define the model
model = Sequential([
    Conv2D(128, (3, 3), activation='relu', input_shape=(10, 700, 1)),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    RepeatVector(max_seq_length),
    LSTM(64, return_sequences=True),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

# Training the model
print("Training model")
model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=300, batch_size=1000)

# Evaluate the model (if you have a test set)
# X_test, Y_test = ...  # Your test data
loss = model.evaluate(X_val, Y_val)
print(f'Test Loss: {loss}')



ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        print(e)
print(tf.__version__)
print(tf.config.list_physical_devices())

Num GPUs Available:  0
2.17.0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]


In [ ]:
model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=300, batch_size=1000)

Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - loss: 4.5191 - val_loss: 4.4832
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.5116 - val_loss: 4.4938
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.5081 - val_loss: 4.4555
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.4670 - val_loss: 4.4512
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.4630 - val_loss: 4.4318
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.4459 - val_loss: 4.3996
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.4165 - val_loss: 4.3817
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.4044 - val_loss: 4.3692
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.3847 - val_loss: 4.3383
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.3437 - val_loss: 4.3547
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.3596 - val_loss: 4.3774
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.3709 - val_loss: 4.3885
Epoch 13/300


In [ ]:
model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=100, batch_size=1000)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.5922 - val_loss: 4.5796
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 4.6034 - val_loss: 4.5818
Epoch 3/100


KeyboardInterrupt: 

In [ ]:
test_index = 150
print(np.shape(X_val[0]))
test_dataset = np.array(X_val[test_index])
test_dataset = test_dataset.reshape(1, 10, 700, 1)
print(np.shape(test_dataset))
print(model.predict(test_dataset))
print(Y_val[test_index])
# print(X_val)

(10, 700, 1)
(1, 10, 700, 1)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[[ 0.47679412]
  [ 4.1134205 ]
  [-0.01030136]]]
[[0.41090518]
 [4.0609484 ]
 [0.        ]]


In [ ]:
save_path = "model.keras"
model.save(save_path)

In [ ]:
model_keras = tf.keras.models.load_model(save_path)
converter = tf.lite.TFLiteConverter.from_keras_model(model_keras)
# Enable resource variables
converter.experimental_enable_resource_variables = True

# Use select TensorFlow ops
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
]

# Disable experimental lower tensor list ops
converter._experimental_lower_tensor_list_ops = False

# Optional: Enable optimization
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# Convert the model
tflite_model = converter.convert()

# Save the TFLite model
with open('my_model.tflite', 'wb') as f:
    f.write(tflite_model)

INFO:tensorflow:Assets written to: C:\Users\thoma\AppData\Local\Temp\tmps1ju3blg\assets


INFO:tensorflow:Assets written to: C:\Users\thoma\AppData\Local\Temp\tmps1ju3blg\assets


Saved artifact at 'C:\Users\thoma\AppData\Local\Temp\tmps1ju3blg'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 10, 700, 1), dtype=tf.float32, name='input_layer')
Output Type:
  TensorSpec(shape=(None, 3, 1), dtype=tf.float32, name=None)
Captures:
  2684426510480: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2684426509712: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2684426509904: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2684426514320: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2684426513936: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2684426515280: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2684426516048: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2684426514512: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2684426515664: TensorSpec(shape=(), dtype=tf.resource, name=None)
