In [1]:
import importData as import_data
import torch
import torch.nn as nn
import torch.optim as optim
import os
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'
from torch.utils.data import DataLoader, TensorDataset, random_split
from sklearn.model_selection import train_test_split
import numpy as np
import random
torch.backends.cuda.matmul.allow_tf32 = True

uuids = ["99AAC7DE-4106-43AB-AA80-F5816AB4DB85", "69508C29-2B15-4230-BE32-328E553EC63D", "2D2247C8-6B76-45BE-AC6B-F177A87ED4EF"]
id = import_data.importData()
d_final, t_final = None, None
for uuid in uuids:
    d, t = id.import_data(uuid, 0.02)
    if d_final is None:
        d_final, t_final = d, t
    else:
        # print("o")
        if len(t_final[0]) == len(t[0]):
            d_final = np.concatenate((d_final, d), axis=0)
            t_final = np.concatenate((t_final, t), axis=0)
        else:
            if len(t_final[0]) < len(t[0]):
                difference = -len(t_final[0]) + len(t[0])
                lengthened_t_final = []
                for i, t_fin in enumerate(t_final):
                    # print(np.shape(t_fin))
                    zeros = np.zeros((difference,1))
                    # print(np.shape(zeros))
                    # print(t_fin)
                    # print(zeros)
                    lengthened_t_final.append(np.concatenate((t_fin, np.zeros((difference,1))), axis=0))
                d_final = np.concatenate((d_final, d), axis=0)
                t_final = np.concatenate((lengthened_t_final, t), axis=0)
            elif len(t_final[0]) > len(t[0]):
                difference = len(t_final[0]) - len(t[0])
                lengthened_t= []
                for i, t_fin in enumerate(t):
                    # print(np.shape(t_fin))
                    zeros = np.zeros((difference,1))
                    # print(np.shape(zeros))
                    # print(t_fin)
                    # print(zeros)
                    lengthened_t.append(np.concatenate((t_fin, np.zeros((difference,1))), axis=0))
                d_final = np.concatenate((d_final, d), axis=0)
                t_final = np.concatenate((t_final, lengthened_t), axis=0)
                



/home/thomas/Documents/ActiveAlarm_Processing/importData.py:126: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trimmed_raw_df["time"] = trimmed_raw_df["time"].apply(lambda x: x - timestamps_df["startTime"][0])
/home/thomas/Documents/ActiveAlarm_Processing/importData.py:161: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_time_dataset["time"] = start_time_dataset["time"] - start_time


[0.0000e+00 2.0000e-02 4.0000e-02 ... 1.0494e+02 1.0496e+02 1.0498e+02]


/home/thomas/Documents/ActiveAlarm_Processing/importData.py:126: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trimmed_raw_df["time"] = trimmed_raw_df["time"].apply(lambda x: x - timestamps_df["startTime"][0])
/home/thomas/Documents/ActiveAlarm_Processing/importData.py:161: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_time_dataset["time"] = start_time_dataset["time"] - start_time


[0.0000e+00 2.0000e-02 4.0000e-02 ... 1.0794e+02 1.0796e+02 1.0798e+02]


/home/thomas/Documents/ActiveAlarm_Processing/importData.py:126: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trimmed_raw_df["time"] = trimmed_raw_df["time"].apply(lambda x: x - timestamps_df["startTime"][0])
/home/thomas/Documents/ActiveAlarm_Processing/importData.py:161: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_time_dataset["time"] = start_time_dataset["time"] - start_time


[0.0000e+00 2.0000e-02 4.0000e-02 ... 1.0494e+02 1.0496e+02 1.0498e+02]


In [2]:
print(np.shape(t_final))
print((d_final[0][6]))

(15205, 4, 1)
[[ 6.47775674e+00]
 [ 2.70528793e-02]
 [ 3.84745598e-02]
 [ 2.15543807e-03]
 [-1.03654618e+00]
 [-1.49318189e-01]
 [ 1.56479767e-01]
 [-8.50135326e-01]
 [-5.02974510e-01]
 [-1.55841962e-01]
 [ 6.48906398e+00]
 [ 1.17388964e-02]
 [ 3.98785472e-02]
 [ 6.11692667e-03]
 [-1.03119101e+00]
 [-1.46497205e-01]
 [ 1.45931826e-01]
 [-8.48792672e-01]
 [-5.08336246e-01]
 [-1.45414412e-01]
 [ 6.50010991e+00]
 [-2.76350975e-03]
 [ 3.38243246e-02]
 [ 2.14740038e-02]
 [-1.02591759e+00]
 [-1.42525469e-01]
 [ 1.35936466e-01]
 [-8.47300887e-01]
 [-5.13532817e-01]
 [-1.35518193e-01]
 [ 6.51166487e+00]
 [-1.21673346e-02]
 [ 2.35096812e-02]
 [ 4.49520350e-02]
 [-1.02085655e+00]
 [-1.37724954e-01]
 [ 1.26773245e-01]
 [-8.45714211e-01]
 [-5.18441737e-01]
 [-1.26433939e-01]
 [ 6.51723790e+00]
 [-1.25410557e-02]
 [ 1.65413618e-02]
 [ 5.23985922e-02]
 [-1.01593914e+00]
 [-1.32271622e-01]
 [ 1.18394599e-01]
 [-8.44025493e-01]
 [-5.23133934e-01]
 [-1.18118197e-01]
 [ 6.52758670e+00]
 [-1.02906227e-02

In [3]:
print(torch.__version__)

2.4.1


In [4]:
# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# Splitting data into training and validation sets
X_train, X_val, Y_train, Y_val = train_test_split(d_final, t_final, test_size=0.2, random_state=42)

# Verify that the split is done correctly
print(f"X_train shape: {np.shape(X_train)}")
print(f"Y_train shape: {np.shape(Y_train)}")
print(f"X_val shape: {np.shape(X_val)}")
print(f"Y_val shape: {np.shape(Y_val)}")

# Convert data to PyTorch tensors
X_train = torch.tensor(X_train, dtype=torch.float32).to(device)
Y_train = torch.tensor(Y_train, dtype=torch.float32).to(device)
X_val = torch.tensor(X_val, dtype=torch.float32).to(device)
Y_val = torch.tensor(Y_val, dtype=torch.float32).to(device)

# Create datasets and dataloaders
train_dataset = TensorDataset(X_train, Y_train)
val_dataset = TensorDataset(X_val, Y_val)

train_loader = DataLoader(train_dataset, batch_size=3000, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=3000)

# Define the model
class CNNLSTMModel(nn.Module):
    def __init__(self, max_seq_length):
        super(CNNLSTMModel, self).__init__()
        self.conv = nn.Conv2d(10, 128, kernel_size=(3, 1))
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(kernel_size=(2, 1))  # Only pool along the height dimension
        self.flatten = nn.Flatten()
        self.fc = nn.Linear(128 * 499, 128)  # Adjusted dimensions after conv and pool
        self.repeat = nn.Linear(128, 128 * max_seq_length)
        self.lstm = nn.LSTM(128, 64, batch_first=True)
        self.fc_out = nn.Linear(64, 1)

    def forward(self, x):
        x = self.conv(x)
        x = self.relu(x)
        x = self.pool(x)
        x = self.flatten(x)
        x = self.relu(self.fc(x))
        x = self.repeat(x)
        x = x.view(-1, max_seq_length, 128)  # Reshape to (batch_size, seq_length, input_size)
        x, _ = self.lstm(x)
        x = self.fc_out(x)
        return x

max_seq_length = Y_train.shape[1]
model = CNNLSTMModel(max_seq_length).to(device)

# Define loss and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training the model
print("Training model")
epochs = 400
for epoch in range(epochs):
    model.train()
    for X_batch, Y_batch in train_loader:
        optimizer.zero_grad()
        outputs = model(X_batch)
        loss = criterion(outputs, Y_batch)
        loss.backward()
        optimizer.step()

    # Validation
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for X_batch, Y_batch in val_loader:
            outputs = model(X_batch)
            loss = criterion(outputs, Y_batch)
            val_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs}, Training Loss: {loss.item()}, Validation Loss: {val_loss / len(val_loader)}")

print("Training complete")

Using device: cuda
X_train shape: (12164, 10, 1000, 1)
Y_train shape: (12164, 4, 1)
X_val shape: (3041, 10, 1000, 1)
Y_val shape: (3041, 4, 1)
Training model
Epoch 1/400, Training Loss: 12.981632232666016, Validation Loss: 12.67840576171875
Epoch 2/400, Training Loss: 11.474629402160645, Validation Loss: 11.210290431976318
Epoch 3/400, Training Loss: 10.9371976852417, Validation Loss: 10.684210777282715
Epoch 4/400, Training Loss: 10.570026397705078, Validation Loss: 10.331651210784912
Epoch 5/400, Training Loss: 10.10010051727295, Validation Loss: 9.864035606384277
Epoch 6/400, Training Loss: 9.76292896270752, Validation Loss: 9.542757034301758
Epoch 7/400, Training Loss: 9.452653884887695, Validation Loss: 9.250274658203125
Epoch 8/400, Training Loss: 9.162354469299316, Validation Loss: 8.982879161834717
Epoch 9/400, Training Loss: 8.936670303344727, Validation Loss: 8.769155979156494
Epoch 10/400, Training Loss: 8.736495018005371, Validation Loss: 8.58027458190918
Epoch 11/400, Trai

In [5]:
# Save the trained model
torch.save(model.state_dict(), "torch_model.pth")

# Convert the model to TorchScript
model.eval()  # Set the model to evaluation mode
example_input = torch.rand(1, 10, 1000, 1).to(device)  # An example input tensor with the same dimensions as your input data
traced_script_module = torch.jit.trace(model, example_input)

# Save the TorchScript model
traced_script_module.save("torch_trace_model.pt")

In [6]:
testuuid = "98006881-B2F0-4B6B-94CF-A21ABE69F21B"


d_test, t_test = id.import_data(testuuid, 0.02)
indices = list(range(len(d_test)))
sampled_indices = random.sample(indices, 1000)
sampled_indices = sorted(sampled_indices)
d_test, t_test = d_test[sampled_indices], t_test[sampled_indices]

new_data = torch.tensor(d_test, dtype=torch.float32).to(device)

# Load the saved model
model = CNNLSTMModel(max_seq_length).to(device)
model.load_state_dict(torch.load("torch_model.pth"))
model.eval()

# Run the model on the new dataset
with torch.no_grad():
    outputs = model(new_data)

# Convert the outputs to a NumPy array
outputs = outputs.cpu().numpy()

# Print the first few predictions
print("Model predictions on new dataset:")
print(outputs)
print("test hypersuccess")

/home/thomas/Documents/ActiveAlarm_Processing/importData.py:126: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trimmed_raw_df["time"] = trimmed_raw_df["time"].apply(lambda x: x - timestamps_df["startTime"][0])
/home/thomas/Documents/ActiveAlarm_Processing/importData.py:161: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  start_time_dataset["time"] = start_time_dataset["time"] - start_time


[0.0000e+00 2.0000e-02 4.0000e-02 ... 1.3294e+02 1.3296e+02 1.3298e+02]
Model predictions on new dataset:
[[[2.0360239 ]
  [5.408114  ]
  [3.9871552 ]
  [0.14982362]]

 [[2.0360239 ]
  [5.408114  ]
  [3.9871552 ]
  [0.14982362]]

 [[2.0360239 ]
  [5.408114  ]
  [3.9871552 ]
  [0.14982362]]

 ...

 [[2.0360239 ]
  [5.408114  ]
  [3.9871552 ]
  [0.14982362]]

 [[2.0360239 ]
  [5.408114  ]
  [3.9871552 ]
  [0.14982362]]

 [[2.0360239 ]
  [5.408114  ]
  [3.9871552 ]
  [0.14982362]]]
test hypersuccess


/tmp/ipykernel_3689/4012897622.py:14: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load("torch_model.pth"))


In [7]:
for i, output in enumerate(outputs):
    print(output, t_test[i])

[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [5.408114  ]
 [3.9871552 ]
 [0.14982362]] [[0.]
 [0.]
 [0.]
 [0.]]
[[2.0360239 ]
 [

: 